// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CompanyEmployees.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241121040655_Second_SeedDataAdded")]
    partial class Second_SeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789012"),
                            Address = "666 SomewhereInUS Rd., New York, NY, 10001",
                            Country = "USA",
                            Name = "Suspicious Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("87654321-4321-4321-4321-210987654321"),
                            Address = "777 SomewhereInCanada Blvd., Edmonton, AB, T6W 1T7",
                            Country = "Canada",
                            Name = "Kinda Suspicious Solutions Ltd"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1de6b78-c874-472e-b664-9012ef42287b"),
                            Age = 0,
                            CompanyId = new Guid("12345678-1234-1234-1234-123456789012"),
                            Name = "Indiana Jones",
                            Position = "Archaeologist"
                        },
                        new
                        {
                            Id = new Guid("2de4ebfc-9b51-42d7-acb8-ba91ffcece47"),
                            Age = 0,
                            CompanyId = new Guid("12345678-1234-1234-1234-123456789012"),
                            Name = "Lara Croft",
                            Position = "Tomb Rider"
                        },
                        new
                        {
                            Id = new Guid("4b276462-ab30-4c60-803d-f93432087f19"),
                            Age = 0,
                            CompanyId = new Guid("87654321-4321-4321-4321-210987654321"),
                            Name = "Jurgen Feller",
                            Position = "NASA Scientist"
                        },
                        new
                        {
                            Id = new Guid("2af845da-d4e1-4e3a-9c31-45e17cd75c2e"),
                            Age = 0,
                            CompanyId = new Guid("87654321-4321-4321-4321-210987654321"),
                            Name = "Mathias Vogel",
                            Position = "Archaeologist"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
